### ISSUE TITLE
Задание 2

### ISSUE THREAD

**Issue by d-qql** [FlyingPotato-131/a-line-of-potatoes#1]
Убрать здесь жесткий оверхед с лишними вычислениями count. 
https://github.com/FlyingPotato-131/a-line-of-potatoes/blob/75a4e20a69ce5bd9804958dcf41d0db3d1897bcf/src/csr-matrix.cpp#L4C1-L22C2

Убрать везде указатели, push_back без предварительного reserve и так далее, в общем все, что написано в https://github.com/MIPT-SLE/UnforgivableCurses

**Comment by FlyingPotato-131** [comment]
исправил
https://github.com/FlyingPotato-131/a-line-of-potatoes/commit/b3aa86252d729ec77cceeab5acb6ee489681d47c
